option(
  'with_webkit',
  description: 'Use webkit for auth via yandex or not (use token)',
  type: 'boolean',
  value: true
)

option(
  'e2k',
  description: 'Optimize build for e2k',
  type: 'boolean',
  value: false
)
option(
  'force-release',
  type: 'boolean',
  value: false
)


option(
  'sdk_only',
  type: 'boolean',
  value: false,
  description: 'build libtape only'
)
option(
  'documentation',
  type: 'boolean',
  value: false,
  description: 'generate documentation with gtk-doc and valadoc'
)
option(
  'introspection',
  type: 'boolean',
  value: true,
  description: 'Whether to build introspection files'
)

# tests
option(
  'token',
  type: 'string',
  value: '',
  description: 'Token for API tests. If empty tests will skipped'
)
