name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'altlinux'
    tags-ignore:
      - '*'

env:
  API_BASE_REPO: rpm https://altlinux.space/api/packages/rirusha/alt/group/libapi-base-nightly.repo x86_64 classic
  CASE_REPO: rpm https://altlinux.space/api/packages/rirusha/alt/group/libcase-nightly.repo x86_64 classic

jobs:
  lint:
    name: Lint
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          make lint

  build-doc-translation:
    name: Build, update translation and upload doc
    runs-on: als-huge
    container: registry.altlinux.org/sisyphus/node:latest
    needs:
      - lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.event_name == 'pull_request' && github.token || secrets.REPO_TOKEN }}

      - name: Install apt-repo
        run: |
          apt-get update
          apt-get install -y apt-repo

      - name: Add liapi-base repo
        run: |
          apt-repo add ${{ env.API_BASE_REPO }}

      - name: Add case repo
        run: |
          apt-repo add ${{ env.CASE_REPO }}

      - name: Install deps
        run: |
          apt-get install meson valadoc gcc vala 'pkgconfig(libadwaita-1)'

      - name: Setup
        run: make setup-ci

      - name: Build
        run: make compile

      - name: Test
        run: make test

      - name: Deploy pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/lib/doc/libtape-vala

  flatpak-build:
    name: Flatpak build and uploading
    runs-on: als-huge
    container: altlinux.space/rirusha/flatpak-builder:latest
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    needs:
      - lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push flatpak app
        uses: alt-hub/actions/build-application@main
        with:
          key-id: ${{ secrets.GPG_KEY_ID }}
          private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          key-grip: ${{ secrets.GPG_KEY_GREP }}
          app-id: space.rirusha.Cassette.Devel
          manifest-path: build-aux/flatpak/space.rirusha.Cassette.Devel.yml
          registry-password: ${{ secrets.TOKEN }}
