name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'altlinux'
    tags-ignore:
      - '*'

env:
  TAPE_REPO: rpm https://altlinux.space/api/packages/rirusha/alt/group/libtape-nightly.repo x86_64 classic
  CASE_REPO: rpm https://altlinux.space/api/packages/rirusha/alt/group/libcase-nightly.repo x86_64 classic

jobs:
  lint-vala:
    name: Check vala files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  lint-blueprint:
    name: Check blueprint files
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/blueprint@main

  build-doc-translation:
    name: Build, update translation and upload doc
    runs-on: als-huge
    container: registry.altlinux.org/sisyphus/node:latest
    needs:
      - lint-vala
      - lint-blueprint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.event_name == 'pull_request' && github.token || secrets.REPO_TOKEN }}

      - name: Install apt-repo
        run: |
          apt-get update
          apt-get install -y apt-repo

      - name: Add tape repo
        run: |
          apt-repo add ${{ env.TAPE_REPO }}

      - name: Add case repo
        run: |
          apt-repo add ${{ env.CASE_REPO }}

      - name: Install deps
        run: |
          apt-get update
          xargs apt-get install -y < ./build-aux/altlinux/build-deps

      - name: Setup
        run: meson setup _build -Dnightly=true

      - name: Build
        run: meson compile -C _build

      - name: Build
        run: meson test -C _build

      - name: Setup git
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@altlinux.space"
          git config --global --add safe.directory '*'

      - name: Update pot file for Weblate
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: |
          has_real_changes() {
            git diff --cached -U0 | grep -E '^[+-]' \
              | grep -Ev '^[+-]{3}' \
              | grep -Ev '^[+-]["#]' \
              | grep -q '.'
          }

          ./po/update_potfiles

          git add .
          git commit -m "i18n: Update POTFILES" || true

          meson compile -C _build cassette-pot
          git add .

          if has_real_changes; then
            git commit -m "i18n: Update .pot file" || true

            meson compile -C _build cassette-update-po

            git add po/*.po
            git commit -m "i18n: Update .po files" || true
          else
            git reset --hard
          fi

          git push

  get-release:
    name: Get release for RPM package
    runs-on: als-tiny

    outputs:
      release: ${{ steps.get_release.outputs.release }}
    steps:
      - name: Get release
        id: get_release
        run: |
          echo "release=$(date +%s)" >> $FORGEJO_OUTPUT

  flatpak-build:
    name: Flatpak build and uploading
    runs-on: als-huge
    container: altlinux.space/rirusha/flatpak-builder:latest
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    needs:
      - lint-vala
      - lint-blueprint
      - get-release
      - build-doc-translation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import gpg
        id: import-gpg
        uses: alt-hub/actions/import-gpg@main
        with:
          private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          key-grip: ${{ secrets.GPG_KEY_GREP }}

      - name: Build Cassette
        run: |
          flatpak-builder --keep-build-dirs --gpg-sign=${{ secrets.GPG_KEY_ID }} --gpg-homedir="${{ steps.import-gpg.outputs.gpg-homedir }}" --disable-rofiles-fuse cassette_app --repo=.flatpak-repo build-aux/flatpak/space.rirusha.Cassette.Devel.yml

          flatpak build-bundle .flatpak-repo --oci cassette_app-image space.rirusha.Cassette.Devel

      - name: Upload images
        env:
          REGISTRY_USERNAME: '<token>'
          REGISTRY_PASSWORD: ${{ secrets.TOKEN }}
          REGISTRY: altlinux.space/rirusha
        run: |
          skopeo login --username=$REGISTRY_USERNAME --password=$REGISTRY_PASSWORD $REGISTRY

          skopeo copy oci:cassette_app-image docker://$REGISTRY/cassette_app

  rpm-build:
    if: github.event_name != 'pull_request'
    name: RPM build and uploading
    runs-on: als-huge
    container: altlinux.space/alt-gnome/hasherc:latest
    needs:
      - lint-vala
      - lint-blueprint
      - get-release
      - build-doc-translation

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build
        run: |
          ./build-aux/altlinux/prepare ${{ needs.get-release.outputs.release }}
          git add .

      - name: Build RPMs
        run: |
          git config --global user.email "hasherc-ci@altlinux.org"
          git config --global user.name "Builder"
          echo "%packager Builder <hasherc-ci@altlinux.org>" > ~/.rpmmacros

          gear-hshc --commit --no-sisyphus-check=gpg,packager --add-source '${{ env.TAPE_REPO }}' --add-source '${{ env.CASE_REPO }}'

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        with:
          directory: ~/.cache/hasherc/cassette/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: cassette-nightly
