name: Daily POTFILES update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-potfiles:
    name: Update
    runs-on: als-tiny
    container: registry.altlinux.org/sisyphus/node:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name "Cassette Helper"
          git config --global user.email "cassette-helper@noreply.altlinux.space"
          git config --global --add safe.directory '*'

      - name: Update POTFILES
        run: |
          make update-potfiles

          git add .
          git commit -m "i18n: Update POTFILES" || true

          git push
