#!/bin/bash
# Should run from project root dir

touch ./libtape/po/unsort-POTFILES.in

find ./libtape/src -iname "*.vala" -type f -exec grep -lrE '_\(|C_|ngettext' {} + | while read file; do echo "${file#./}" >> ./libtape/po/unsort-POTFILES.in; done

cat ./libtape/po/unsort-POTFILES.in | sort | uniq > ./libtape/po/POTFILES.in

rm ./libtape/po/unsort-POTFILES.in

# To add translation, please use Damned Lies service https://l10n.gnome.org/
