#!/usr/bin/bash -ex

mkdir -p .gear
cp -a build-aux/altlinux/rules ./.gear/

version=$(./build-aux/get_meson_version)
release=1.$1

sed -e "s/@VERSION@/${version}/g" \
    -e "s/@RELEASE@/${release}/g" \
    build-aux/altlinux/cassette.spec.in > cassette.spec

add_changelog cassette.spec -e '- Regular build.'
